export const AmiriFont = {
  vfs: {
    "Amiri-Regular.ttf":
      "AAEAAAASAQAABAAgR0RFRrRCsIIAAJ0AAAAYGNtYXAXUdcDAACDAAAANmN2dCAAAAAA" +
      "AADsAAAAlmdhc3AABgAAAAA9AAAACmdseWZpAAAAAAAnAAAAMGhlYWQKuWACAAAEAAAA" +
      "JGhoZWESiQcoAAAPAAAANmhtdHgAAAAAAAAAQAAAACRsb2NhAVYAAgAAEAAAAAxtYXhw" +
      "AAAAAQAAAgAAAAAgbmFtZQAAAAAAAAAIAAAAAFBvc3QAAAEAAAAMcHJlcAAACAAAAAQI" +
      "AAAACAAEAAAAAAAAAAQAAAAAAAAABAAAAAQAAAFcAAQAAAAAFAAcAAQAAAAAFAAkADAAE" +
      "AAAAAAIAAQAAAAAAAAAIAAAAAgAAAAEAAAABAAD/jAAEAAEAAAAQAAAAAAAAAAEAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAA=="
  }
};
